### ISSUE TITLE
aliasing fd causes Search Directory to hang

### ISSUE THREAD

**Issue by Susensio** [PatrickF1/fzf.fish#281]
I have fd aliased to a less pager, like so:

```fish
function fd --wraps=fdfind --description 'alias fd=fdfind'
  if isatty stdout
    command fdfind --color always $argv | less
  else
    command fdfind $argv
  end
end
```

This is causing Directory Search to hang until all results have been found.

#280 Fixes than by checking that unwrapped `fd` is called.

**Comment by PatrickF1** [comment]
Hi Susensio, I wonder if it's possible fish functions don't support streaming in pipelines, so they block until they have received all the data? Anyway, I don't think this isn't a bug with fzf.fish

**Comment by PatrickF1** [comment]
Does Search Directory still hang if, instead of creating a wrapper function for fd, you use an alias?

**Comment by PatrickF1** [comment]
Oh it probably does because fish aliases basically creates a function unlike other shells. Okay yeah, let's add `command fd` I'll update the docs to tell people to symlink instead of aliasing. However, I don't want to look for fdfind and use it if it's available because Search Directory is becoming monstrous and I despise maintaining it.

**Comment by Susensio** [comment]
I've submitted a PR #282 that solves the `fd` or `fdfind` binary problem without aliases. I think it's fairy simple and doesn't add much complexity.

The problem with #280 and symlink that you suggest is that it would be a breaking change and suddenly the extension will stop working for the people that use fish aliases
