### ISSUE TITLE
Idea: consolidate under single keystroke

### ISSUE THREAD

**Issue by pikeas** [PatrickF1/fzf.fish#79]
Great plugin, especially loving the recent QOL improvements in v5!

Have you considered using a single keystroke to enter "fzf mode"? I use ctrl-f the most by far, so my brain has rewired to think of that keystroke as fzf-ified <tab>. On the comparatively rarer occasions I'm committing code or want to check environment variables, I find myself typing `git add|set|ssh <ctrl-f>` only to be surprised by a list of files via fd. It then takes a few tries to remember the additional keybindings.

Your plugin has done *too* good a job of integrating fzf into fish, perhaps you can take it even further and turn it into a seamless "do what I mean" contextualized fuzzy tab completion?

**Comment by PatrickF1** [comment]
Hi @pikeas, thanks for the compliment!
I'm not sure what you mean. Are you saying you want a keystroke that enters fzf mode where you can then execute other keybindings to do other commands"

**Comment by pikeas** [comment]
In the current implementation, ctrl-f isn't context-dependent, it always runs fzf on the list of files output by fd. Tab completion, on the other hand, is context-dependent (command completion, ssh host completion, filename completion, etc).

So my idea is to combine these - context-aware input a la tab completion, fuzzy filtering/preview/etc a la fzf. 

* `git add <ctrl-f>` -> current behavior from `__fzf_search_git_status`
* `set <ctrl-f>` -> current behavior from `__fzf_search_shell_variables`
* (other possible contexts, for example `ssh <ctrl-f>`
* (default context) `<ctrl-f>` -> current behavior from `__fzf_search_current_dir`

**Comment by PatrickF1** [comment]
Hi @pikeas, what a wonderful idea! I really appreciate your creative thinking and I wish I had the time to expand the scope of my plugin so I could implement it. 

Let me explain more concretely why this is very difficult and I simply don't have the bandwidth since this is just a hobby for me
- The number of possible contexts to account for are very numerous.
- Checking for all the different contexts will result in complex, convoluted logic.
- Many contexts will be ambiguous. e.g. `vim <ctrl-f>` could be either `__fzf_search_git_status` or `__fzf_search_current_dir`. Sure, I could just pick one arbitrarily but from the user's perspective, they wouldn't be able to know and remember intuitively which command gets executed in those arbitrary contexts.
- Since the key bindings are mnemonic, I have hope that you'll soon develop the muscle memory to trigger the right one when you need it!
